### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by altryne** [Aminerman/vue-kinesis#40] opened 2020-09-19 05:47 UTC
Hey there, it looks like https://aminerman.com/ is down and there's no demo nor usage for this package. 
Can you please host the demo on github.io 🙏

**Comment by venkivijay** [comment] 2020-10-02 07:09
@Aminerman Can you please resolve this issue?

**Comment by Maus3rSR** [comment] 2020-10-14 08:07
https://aminerman.com/kinesis

**Comment by venkivijay** [comment] 2020-10-14 08:30
@Maus3rSR We know the link to the demo site. The issue is that it was down. Anyways thanks. 
@altryne Now that the site is up and running this issue can be closed.

**Comment by Aminerman** [comment] 2020-11-08 20:36
@altryne Thanks for letting me know. Indeed the website was down for a little while. As you said it might be better to host it on github.io and add demos directly in the package. 
I'll do this soon. I'm sorry for the lack of updates lately, some personal issues made me be away from programming for a while.
I'll close the issue when this is all done.

**Closed** 2020-11-10 21:50 UTC
